export interface Booth {
  booth_number: string;
  brewery_name: string;
  area: string;
  row: number;
  col: number;
  color_code: string;
}

export interface Sake {
  booth_number: string;
  company_name: string;
  isLimited: boolean;
  isPaid: boolean;
  category: string;
  type: string;
  name: string;
}

export const boothData: Booth[] = [
  { booth_number: '1', brewery_name: '関原酒造', area: '中越エリア', row: 1, col: 1, color_code: '#d4e4c9' },
  { booth_number: '2', brewery_name: '柏露酒造', area: '中越エリア', row: 1, col: 2, color_code: '#d4e4c9' },
  { booth_number: '3', brewery_name: '八海醸造', area: '中越エリア', row: 1, col: 3, color_code: '#d4e4c9' },
  { booth_number: '15', brewery_name: '玉川酒造', area: '中越エリア', row: 2, col: 1, color_code: '#d4e4c9' },
  { booth_number: '4', brewery_name: '福顔酒造', area: '中越エリア', row: 1, col: 4, color_code: '#d4e4c9' },
  { booth_number: '17', brewery_name: '河忠酒造', area: '中越エリア', row: 2, col: 3, color_code: '#d4e4c9' },
  { booth_number: '16', brewery_name: '石塚酒造', area: '中越エリア', row: 2, col: 2, color_code: '#d4e4c9' },
  { booth_number: '18', brewery_name: '苗場酒造', area: '中越エリア', row: 2, col: 4, color_code: '#d4e4c9' },
  { booth_number: '5', brewery_name: '池浦酒造', area: '中越エリア', row: 1, col: 5, color_code: '#d4e4c9' },
  { booth_number: '19', brewery_name: '緑川酒造', area: '中越エリア', row: 2, col: 5, color_code: '#d4e4c9' },
  { booth_number: '6', brewery_name: '白龍酒造', area: '中越エリア', row: 1, col: 6, color_code: '#d4e4c9' },
  { booth_number: '20', brewery_name: '諸橋酒造', area: '中越エリア', row: 2, col: 6, color_code: '#d4e4c9' },
  { booth_number: '7', brewery_name: '松乃井酒造場', area: '中越エリア', row: 1, col: 7, color_code: '#d4e4c9' },
  { booth_number: '21', brewery_name: '長谷川酒造', area: '中越エリア', row: 2, col: 7, color_code: '#d4e4c9' },
  { booth_number: '8', brewery_name: '中川酒造', area: '中越エリア', row: 1, col: 8, color_code: '#d4e4c9' },
  { booth_number: '22', brewery_name: '原酒造', area: '中越エリア', row: 2, col: 8, color_code: '#d4e4c9' },
  { booth_number: '9', brewery_name: '恩田酒造', area: '中越エリア', row: 1, col: 9, color_code: '#d4e4c9' },
  { booth_number: '23', brewery_name: '高の井酒造', area: '中越エリア', row: 2, col: 9, color_code: '#d4e4c9' },
  { booth_number: '10', brewery_name: '青木酒造', area: '中越エリア', row: 1, col: 10, color_code: '#d4e4c9' },
  { booth_number: '24', brewery_name: '越銘醸', area: '中越エリア', row: 2, col: 10, color_code: '#d4e4c9' },
  { booth_number: '11', brewery_name: 'マスカガミ', area: '中越エリア', row: 1, col: 11, color_code: '#d4e4c9' },
  { booth_number: '25', brewery_name: '魚沼酒造', area: '中越エリア', row: 2, col: 11, color_code: '#d4e4c9' },
  { booth_number: '12', brewery_name: '新潟銘醸', area: '中越エリア', row: 1, col: 12, color_code: '#d4e4c9' },
  { booth_number: '26', brewery_name: 'お福酒造', area: '中越エリア', row: 2, col: 12, color_code: '#d4e4c9' },
  { booth_number: '13', brewery_name: '津南醸造', area: '中越エリア', row: 1, col: 13, color_code: '#d4e4c9' },
  { booth_number: '27', brewery_name: '雪椿酒造', area: '中越エリア', row: 2, col: 13, color_code: '#d4e4c9' },
  { booth_number: '14', brewery_name: '阿部酒造', area: '中越エリア', row: 1, col: 14, color_code: '#d4e4c9' },
  { booth_number: '28', brewery_name: '朝日酒造', area: '中越エリア', row: 2, col: 14, color_code: '#d4e4c9' },
  { booth_number: '29', brewery_name: '吉乃川', area: '中越エリア', row: 3, col: 1, color_code: '#d4e4c9' },
  { booth_number: '42', brewery_name: '葵酒造', area: '中越エリア', row: 4, col: 1, color_code: '#d4e4c9' },
  { booth_number: '30', brewery_name: '雪と里山醸造所', area: '中越エリア', row: 3, col: 2, color_code: '#d4e4c9' },
  { booth_number: '43', brewery_name: '栃倉酒造', area: '中越エリア', row: 4, col: 2, color_code: '#d4e4c9' },
  { booth_number: '31', brewery_name: '武蔵野酒造', area: '上越エリア', row: 3, col: 3, color_code: '#d3dbe3' },
  { booth_number: '44', brewery_name: '加藤酒店', area: '佐渡エリア', row: 4, col: 3, color_code: '#d9c876' },
  { booth_number: '32', brewery_name: '上越酒造', area: '上越エリア', row: 3, col: 4, color_code: '#d3dbe3' },
  { booth_number: '45', brewery_name: '頚城酒造', area: '上越エリア', row: 4, col: 4, color_code: '#d3dbe3' },
  { booth_number: '33', brewery_name: '竹田酒造店', area: '上越エリア', row: 3, col: 5, color_code: '#d3dbe3' },
  { booth_number: '46', brewery_name: '逸見酒造', area: '佐渡エリア', row: 4, col: 5, color_code: '#d9c876' },
  { booth_number: '34', brewery_name: '新潟第一酒造', area: '上越エリア', row: 3, col: 6, color_code: '#d3dbe3' },
  { booth_number: '47', brewery_name: '猪又酒造', area: '上越エリア', row: 4, col: 6, color_code: '#d3dbe3' },
  { booth_number: '-', brewery_name: 'さかすけ', area: 'その他', row: 4, col: 7, color_code: '#ffffff' },
  { booth_number: '-', brewery_name: 'おちょこ洗浄コーナー', area: 'その他', row: 3, col: 7, color_code: '#ffffff' },
  { booth_number: '35', brewery_name: '千代の光酒造', area: '上越エリア', row: 3, col: 8, color_code: '#d3dbe3' },
  { booth_number: '48', brewery_name: '妙高酒造', area: '上越エリア', row: 4, col: 8, color_code: '#d3dbe3' },
  { booth_number: '36', brewery_name: '鮎正宗酒造', area: '上越エリア', row: 3, col: 9, color_code: '#d3dbe3' },
  { booth_number: '49', brewery_name: '田中酒造', area: '上越エリア', row: 4, col: 9, color_code: '#d3dbe3' },
  { booth_number: '37', brewery_name: 'よしかわ杜氏の郷', area: '上越エリア', row: 3, col: 10, color_code: '#d3dbe3' },
  { booth_number: '50', brewery_name: '丸山酒造場', area: '上越エリア', row: 4, col: 10, color_code: '#d3dbe3' },
  { booth_number: '38', brewery_name: '尾畑酒造', area: '佐渡エリア', row: 3, col: 11, color_code: '#d9c876' },
  { booth_number: '51', brewery_name: '田原酒造', area: '上越エリア', row: 4, col: 11, color_code: '#d3dbe3' },
  { booth_number: '39', brewery_name: '代々菊醸造', area: '上越エリア', row: 3, col: 12, color_code: '#d3dbe3' },
  { booth_number: '52', brewery_name: '加藤酒造', area: '上越エリア', row: 4, col: 12, color_code: '#d3dbe3' },
  { booth_number: '40', brewery_name: '加賀の井酒造', area: '上越エリア', row: 3, col: 13, color_code: '#d3dbe3' },
  { booth_number: '53', brewery_name: '小山酒造店', area: '上越エリア', row: 4, col: 13, color_code: '#d3dbe3' },
  { booth_number: '41', brewery_name: '加茂錦酒造', area: '中越エリア', row: 3, col: 14, color_code: '#d4e4c9' },
  { booth_number: '54', brewery_name: '天領盃酒造', area: '佐渡エリア', row: 4, col: 14, color_code: '#d9c876' },
  { booth_number: '55', brewery_name: '麒麟山酒造', area: '下越エリア', row: 5, col: 1, color_code: '#f0ced9' },
  { booth_number: '69', brewery_name: '石本酒造', area: '下越エリア', row: 6, col: 1, color_code: '#f0ced9' },
  { booth_number: '56', brewery_name: 'たからやま醸造', area: '下越エリア', row: 5, col: 2, color_code: '#f0ced9' },
  { booth_number: '70', brewery_name: '王紋酒造', area: '下越エリア', row: 6, col: 2, color_code: '#f0ced9' },
  { booth_number: '57', brewery_name: 'ラグーンブリュワリー', area: '下越エリア', row: 5, col: 3, color_code: '#f0ced9' },
  { booth_number: '71', brewery_name: '菊水酒造', area: '下越エリア', row: 6, col: 3, color_code: '#f0ced9' },
  { booth_number: '58', brewery_name: '越後鶴亀', area: '下越エリア', row: 5, col: 4, color_code: '#f0ced9' },
  { booth_number: '72', brewery_name: '金升酒造', area: '下越エリア', row: 6, col: 4, color_code: '#f0ced9' },
  { booth_number: '59', brewery_name: 'ふじの井酒造', area: '下越エリア', row: 5, col: 5, color_code: '#f0ced9' },
  { booth_number: '73', brewery_name: '金鶴盃酒造', area: '下越エリア', row: 6, col: 5, color_code: '#f0ced9' },
  { booth_number: '60', brewery_name: 'DHC酒造', area: '下越エリア', row: 5, col: 6, color_code: '#f0ced9' },
  { booth_number: '74', brewery_name: '越後桜酒造', area: '下越エリア', row: 6, col: 6, color_code: '#f0ced9' },
  { booth_number: '61', brewery_name: '弥彦酒造', area: '下越エリア', row: 5, col: 7, color_code: '#f0ced9' },
  { booth_number: '75', brewery_name: '大洋酒造', area: '下越エリア', row: 6, col: 7, color_code: '#f0ced9' },
  { booth_number: '62', brewery_name: '今代司酒造', area: '下越エリア', row: 5, col: 8, color_code: '#f0ced9' },
  { booth_number: '76', brewery_name: '越後酒造場', area: '下越エリア', row: 6, col: 8, color_code: '#f0ced9' },
  { booth_number: '63', brewery_name: '近藤酒造', area: '下越エリア', row: 5, col: 9, color_code: '#f0ced9' },
  { booth_number: '77', brewery_name: '塩川酒造', area: '下越エリア', row: 6, col: 9, color_code: '#f0ced9' },
  { booth_number: '64', brewery_name: '高野酒造', area: '下越エリア', row: 5, col: 10, color_code: '#f0ced9' },
  { booth_number: '78', brewery_name: '越つかの酒造', area: '下越エリア', row: 6, col: 10, color_code: '#f0ced9' },
  { booth_number: '65', brewery_name: '峰乃白梅酒造', area: '下越エリア', row: 5, col: 11, color_code: '#f0ced9' },
  { booth_number: '79', brewery_name: '下越酒造', area: '下越エリア', row: 6, col: 11, color_code: '#f0ced9' },
  { booth_number: '66', brewery_name: 'サケイアイ', area: '佐渡エリア', row: 5, col: 12, color_code: '#d9c876' },
  { booth_number: '80', brewery_name: '白龍酒造', area: '下越エリア', row: 6, col: 12, color_code: '#f0ced9' },
  { booth_number: '67', brewery_name: '君の井酒造', area: '上越エリア', row: 5, col: 13, color_code: '#d3dbe3' },
  { booth_number: '81', brewery_name: '笹祝酒造', area: '下越エリア', row: 6, col: 13, color_code: '#f0ced9' },
  { booth_number: '68', brewery_name: '宮尾酒造', area: '下越エリア', row: 5, col: 14, color_code: '#f0ced9' },
  { booth_number: '82', brewery_name: '北雪酒造', area: '佐渡エリア', row: 6, col: 14, color_code: '#d9c876' },
];


export const sakeData: Sake[] = [
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '雪中貯蔵 純米生原酒 想いひおこせば' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '雪中貯蔵 純米吟醸 想いひおこせば' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸 越後長岡藩' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '杜氏の挑戦 巨峰' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '杜氏の挑戦 シャルドネ' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '杜氏の挑戦 ライム' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'SEKIHARA 日本酒で造った巨峰酒' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後長岡藩 日本酒で造った巨峰酒(花火ラベル)' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: true, isPaid: false, category: 'リキュール', type: 'リキュール', name: '酒カクテル シャインマスカット' },
  { booth_number: '1', company_name: '関原酒造(株)', isLimited: true, isPaid: false, category: 'リキュール', type: 'リキュール', name: '酒カクテル マンゴー' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '発泡', name: 'CHAL-008 白麴スパークリング' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '普通酒', name: 'CHAL-009 柱仕込み Act' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: true, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'CHAL-010 長期熟成梅酒' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '柏露 純米大吟醸無濾過生貯蔵原酒' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '発泡純米清酒 柏露花火' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '発泡純米清酒 柏露花火' },
  { booth_number: '2', company_name: '柏露酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '柏露 W柚子' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: true, category: '清酒', type: '特別本醸造', name: '特別本醸造 八海山 ブルーボトル' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: '唎酒 Rishu 春紫菀(ハルジオン) 2025BY' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: '唎酒 Rishu 黄菖蒲(キショウブ) 2025BY' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: '唎酒 Rishu 立葵(タチアオイ) 2025BY' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '唎酒 Rishu UNITED ARROWS 2025BY' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 ニセコ蝦夷富士' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '吟醸 ニセコ蝦夷富士' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '魚沼で候' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸 八海山 55%' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 八海山 雪の中の酒' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 八海山 雪室貯蔵三年' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 八海山 しぼりたて原酒 越後で候' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '瓶内二次発酵酒 八海山 白麹あわ' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '瓶内二次発酵酒 八海山 白麹あわ' },
  { booth_number: '3', company_name: '八海醸造(株)', isLimited: false, isPaid: false, category: 'みりん', type: 'みりん', name: '本みりん 三年熟成品 麹の蜜' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'ウイスキー樽で貯蔵した日本酒FUKUGAO。' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'バーボン樽で貯蔵した日本酒FUKUGAO。' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: 'ブランデー樽で貯蔵した日本酒FUKUGAO。' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: '洋酒樽で貯蔵した日本酒3本セット' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'ルレクチェのお酒' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'ルレクチェのお酒' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '極甘めっちゃ甘口。FUKUGAO' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'セット売り', name: '福顔リキュール3本セット' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '福顔の梅酒' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: true, isPaid: true, category: 'リキュール', type: 'リキュール', name: '福顔の梅酒にごり' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: true, isPaid: true, category: 'リキュール', type: 'リキュール', name: 'ブランデー樽で貯蔵した梅酒。' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '只今さんじょう 特別本醸造' },
  { booth_number: '4', company_name: '福顔酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '吟醸 越後五十嵐川' },
  { booth_number: '5', company_name: '池浦酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '和楽互尊 大吟醸 無濾過生原酒' },
  { booth_number: '5', company_name: '池浦酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '和楽互尊 純米吟醸 原酒' },
  { booth_number: '5', company_name: '池浦酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '和楽互尊 雪割草の里' },
  { booth_number: '5', company_name: '池浦酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '和楽互尊 にごり生酒' },
  { booth_number: '5', company_name: '池浦酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '和楽互尊 金印' },
  { booth_number: '5', company_name: '池浦酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '天上大風' },
  { booth_number: '6', company_name: '白瀧酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '湊屋藤助 純米大吟醸 無濾過原酒 おりがらみ' },
  { booth_number: '6', company_name: '白瀧酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '上善如水 純米吟醸' },
  { booth_number: '6', company_name: '白瀧酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'キウイ由来酵母 by jozen 純米' },
  { booth_number: '6', company_name: '白瀧酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '淡麗辛口魚沼 純米' },
  { booth_number: '6', company_name: '白瀧酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '白瀧 SEVEN 純米大吟醸 原酒 25%' },
  { booth_number: '6', company_name: '白瀧酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '白瀧 SEVEN 純米大吟醸 原酒 25%' },
  { booth_number: '7', company_name: '(株)松乃井酒造場', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '越淡麗おりおり生' },
  { booth_number: '7', company_name: '(株)松乃井酒造場', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米おりおり生' },
  { booth_number: '7', company_name: '(株)松乃井酒造場', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: 'あらばしり新酒' },
  { booth_number: '7', company_name: '(株)松乃井酒造場', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: 'カップ松乃井' },
  { booth_number: '7', company_name: '(株)松乃井酒造場', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: 'スーパー本醸造' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃白雁 黒松' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃白雁 黒松' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃白雁 黒松かめぐち生原酒' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '越乃白雁 本醸造にごり酒' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越乃白雁 純米' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越乃白雁 純米大吟醸 無濾過生原酒' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越乃白雁 純米大吟醸 おりがらみ' },
  { booth_number: '8', company_name: '中川酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '越乃白雁 大吟醸 KH40(三年熟成)' },
  { booth_number: '9', company_name: '恩田酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '舞鶴鼓 88DIG' },
  { booth_number: '9', company_name: '恩田酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '舞鶴URA鼓 純米吟醸 無濾過生' },
  { booth_number: '9', company_name: '恩田酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '米の恩返し EP1' },
  { booth_number: '9', company_name: '恩田酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '米の恩返し EP2' },
  { booth_number: '9', company_name: '恩田酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '舞鶴鼓 88WHITE SWEET' },
  { booth_number: '9', company_name: '恩田酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '舞鶴鼓 純米大吟醸生原酒' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '鶴齢 純米大吟醸' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '鶴齢 純米大吟醸 雪室貯蔵' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '鶴齢 純米吟醸' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '鶴齢 吟醸生酒' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '雪男 純米酒' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '鶴齢の梅酒 純米吟醸仕込み' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '限定大吟醸 牧之' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '鶴齢 純米大吟醸東条産山田錦37%精米' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '鶴齢 イヤーズボトル2025' },
  { booth_number: '10', company_name: '青木酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '鶴齢 イヤーズボトル2022' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: true, isPaid: false, category: '清酒', type: '普通酒', name: 'F40 Shizuku' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: 'F40' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: 'S30 大吟醸' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: 'F50 辛口' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'J55 Sokujo' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'J50 G' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: 'F60 G' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '萬寿鏡の梅酒' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '萬寿鏡の柚子酒' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: 'アルファベットライン300ml×3本セット' },
  { booth_number: '11', company_name: '(株)マスカガミ', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '第96回関東信越国税局 吟醸の部 優秀賞受賞酒' },
  { booth_number: '12', company_name: '新潟銘醸(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '直汲み長さん' },
  { booth_number: '12', company_name: '新潟銘醸(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '桜もよう' },
  { booth_number: '12', company_name: '新潟銘醸(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'デリシャス長さん 生原酒' },
  { booth_number: '12', company_name: '新潟銘醸(株)', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: '錦鯉カップ3本セット' },
  { booth_number: '13', company_name: '津南醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'GO GRANDCLASS 魚沼コシヒカリEdition' },
  { booth_number: '13', company_name: '津南醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '郷(GO) DINER' },
  { booth_number: '13', company_name: '津南醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: 'つなん 藍' },
  { booth_number: '13', company_name: '津南醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'つなん 黄金' },
  { booth_number: '13', company_name: '津南醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: 'GO PINボトル 3本セット' },
  { booth_number: '13', company_name: '津南醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: 'GO POCKET 6個セット' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '非公開', name: 'あべ ゴールド(白)ラベル 無濾過生原酒直汲み 通称: Firstclass(専用箱、袋)' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '非公開', name: 'あべ ゴールド(黒)ラベル 無濾過生原酒直汲み 通称:Firstclass(専用箱、袋)' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: 'あべ ゴールド(白)ラベル 生原酒(箱つき)' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: 'あべ ゴールド(黒)ラベル 生原酒(箱つき)' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: 'REGULUS 直汲み無濾過生原酒' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: 'あべ++' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: '謎酒(直売所専用商品)' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: false, isPaid: true, category: 'リキュール', type: 'リキュール', name: 'ウメ(先行販売)' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: true, category: 'その他', type: 'その他の醸造酒', name: 'コーラSAKE' },
  { booth_number: '14', company_name: '阿部酒造(株)', isLimited: true, isPaid: true, category: 'その他', type: '雑酒', name: 'ユズスパーク' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '大吟醸原酒 雪中貯蔵前 越後ゆきくら' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸原酒 雪中貯蔵前 目黒五郎助' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米酒 ガラパゴス4TH DIMENTION' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸無濾過生原酒 しぼりたてイットキー' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '本醸造 魚沼玉風味' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後武士' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後武士梅酒' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後武士エイジドインオーク' },
  { booth_number: '15', company_name: '玉川酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'ゆずの酒UZ' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: 'ヒメノイ yamij直取り生原酒' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: 'ヒメノイ reculaおりがらみ生原酒' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: 'ヒメノイ nisaki直取り生原酒' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: 'ヒメノイ ishoniおりがらみ生原酒' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '越後高柳 さわがに目覚め' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '初しぼりかめぐち酒' },
  { booth_number: '16', company_name: '石塚酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: 'ヒメノイ wassa にごり生原酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '酒の陣限定 想天坊 高嶺錦 純米大吟醸 無濾過生原酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '酒の陣限定 想天坊 越淡麗 大吟醸 無濾過生原酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '酒の陣限定 想天坊 越淡麗 純米吟醸 生原酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '想天坊 純米にごり生酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '想天坊 高嶺錦 辛口純米吟醸 生原酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '想天坊 じゃんげ 極辛 火入原酒' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '想天坊 じゃんげ 極辛 生' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '想天坊 じゃんげ 超辛口二十度生(赤蛇)' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '想天坊 じゃんげ 超辛口 純米生原酒(蛇薔薇)' },
  { booth_number: '17', company_name: '河忠酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '想天坊 じゃんげ 香る辛口 香辛 純米吟醸(黄蛇)' },
  { booth_number: '18', company_name: '苗場酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'ゆきのまゆ 山田錦40' },
  { booth_number: '18', company_name: '苗場酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'ゆきのまゆ 春' },
  { booth_number: '18', company_name: '苗場酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '深然 無濾過生原酒' },
  { booth_number: '18', company_name: '苗場酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '苗場山 生酒' },
  { booth_number: '18', company_name: '苗場酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: 'ゆきのまゆ 柱焼酎仕込み' },
  { booth_number: '19', company_name: '緑川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '大吟醸 緑川' },
  { booth_number: '19', company_name: '緑川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '緑川Cask Collection SPANISH OAK FINISH' },
  { booth_number: '19', company_name: '緑川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '霞しぼり 緑川' },
  { booth_number: '19', company_name: '緑川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '熱燗酒 正宗' },
  { booth_number: '19', company_name: '緑川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米 緑川' },
  { booth_number: '20', company_name: '諸橋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '越乃景虎 超辛口大吟醸 無濾過生原酒' },
  { booth_number: '20', company_name: '諸橋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越乃景虎 春陽 純米酒' },
  { booth_number: '20', company_name: '諸橋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越乃景虎 純米しぼりたて生酒' },
  { booth_number: '20', company_name: '諸橋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃景虎 龍生酒' },
  { booth_number: '20', company_name: '諸橋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃景虎 超辛口' },
  { booth_number: '20', company_name: '諸橋酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越乃景虎 梅酒' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '越後雪紅梅 大吟醸雫しぼり 氷温熟成' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越後雪紅梅 純米大吟醸 越淡麗仕込' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越後雪紅梅 純米大吟醸 越淡麗仕込' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越後雪紅梅 純米大吟醸 美山錦' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越後雪紅梅 純米大吟醸 美山錦' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越後雪紅梅 四季を旅するお酒 悠久山の桜' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越後雪紅梅 四季を旅するお酒 悠久山の桜' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越後雪紅梅 四季を旅するお酒 雪の酒蔵' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越後雪紅梅 四季を旅するお酒 雪の酒蔵' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越後雪紅梅 四季を旅するお酒 春夏秋冬セット(300ml 4本)' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '越後雪紅梅 手ぬぐい包み(300ml 2本セット)' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越後雪紅梅 純米吟醸 にごり' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '越後雪紅梅 純米吟醸 中取り原酒' },
  { booth_number: '21', company_name: '長谷川酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '越後雪紅梅 大吟醸雫しぼり おりがらみ' },
  { booth_number: '22', company_name: '原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '発泡性純米酒 あわっしゅ' },
  { booth_number: '22', company_name: '原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '寒仕込み純米大吟醸無濾過生原酒' },
  { booth_number: '22', company_name: '原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米90PINK' },
  { booth_number: '22', company_name: '原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸にごり酒' },
  { booth_number: '22', company_name: '原酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: 'Qn(きゅん)おりがらみ' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '田友 純米大吟醸 手造りプレミアム' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '田友 特別純米 手造りプレミアム' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '田友 特別純米' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '田友 純米吟醸 淡の雫生原酒' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '蔵人の盗み酒' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '2026にいがた酒の陣限定 直汲み純米大吟醸生原酒' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: '2026にいがた酒の陣限定 生原酒' },
  { booth_number: '23', company_name: '高の井酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '二十年の眠り' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越の鶴 壱醸21 純米大吟醸' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 越の鶴 鑑評会出品酒' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '越の鶴 壱醸 純米酒' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越の鶴 本正 亀口直取り' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '別撰 越の鶴' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越の鶴 本正 亀口直取り' },
  { booth_number: '24', company_name: '越銘醸(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 ドメーヌ 越の鶴' },
  { booth_number: '25', company_name: '魚沼酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '特別本醸造 天神囃子' },
  { booth_number: '25', company_name: '魚沼酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米酒 天神囃子' },
  { booth_number: '25', company_name: '魚沼酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸酒 天神囃子' },
  { booth_number: '25', company_name: '魚沼酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: 'にごり酒 天神囃子' },
  { booth_number: '25', company_name: '魚沼酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '特別純米無濾過生原酒' },
  { booth_number: '25', company_name: '魚沼酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '純米吟醸無濾過生原酒' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '一本〆純米大吟醸生原酒磨き40' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越淡麗純米大吟醸生原酒磨き40' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '荒走り大吟醸生原酒' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '荒走り純米大吟醸生原酒' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '荒走り純米吟醸生原酒' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越乃福梅完熟梅酒' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越乃福梅完熟にごり梅酒' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後の雪どけ ヨーグルトリキュール' },
  { booth_number: '26', company_name: 'お福酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後の雪どけ ヨーグルトリキュール' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '男前 純米大吟醸 2本セット 蕎麦猪口付き 限定100セット' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '男前 純米大吟醸 ―荒走り―' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '男前 純米大吟醸 ―責め―' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'TAiiiiCHi 純米大吟醸 蔵付酵母 DP' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 魚沼産コシヒカリ 雪椿' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越乃雪椿 グランキュヴェ' },
  { booth_number: '27', company_name: '雪椿酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越乃雪椿 純米大吟醸 月の玉響' },
  { booth_number: '28', company_name: '朝日酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '久保田 萬寿 無濾過生原酒' },
  { booth_number: '28', company_name: '朝日酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '久保田 萬寿' },
  { booth_number: '28', company_name: '朝日酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '久保田 千寿' },
  { booth_number: '28', company_name: '朝日酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '久保田 スパークリング' },
  { booth_number: '28', company_name: '朝日酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '久保田 純米吟醸にごり' },
  { booth_number: '29', company_name: '吉乃川(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '冷や生' },
  { booth_number: '29', company_name: '吉乃川(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米 極上吉乃川' },
  { booth_number: '29', company_name: '吉乃川(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '特別栽培米 五百万石 純米吟醸無濾過原酒(しぼりたて)' },
  { booth_number: '29', company_name: '吉乃川(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '酒蔵淡雪プレミアム' },
  { booth_number: '29', company_name: '吉乃川(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '長期熟成古酒 悠久乃杜2014' },
  { booth_number: '29', company_name: '吉乃川(株)', isLimited: false, isPaid: true, category: '清酒', type: 'セット売り', name: 'みなも飲み比べセット' },
  { booth_number: '30', company_name: '雪と里山醸造所', isLimited: true, isPaid: true, category: 'その他', type: 'その他の醸造酒', name: 'Snow Satoyama Sake - 里山マリアージュ The Sigunature(Sweet)' },
  { booth_number: '30', company_name: '雪と里山醸造所', isLimited: true, isPaid: true, category: 'その他', type: 'その他の醸造酒', name: 'Snow Satoyama Sake - 里山マリアージュ The Sigunature(Dry)' },
  { booth_number: '30', company_name: '雪と里山醸造所', isLimited: true, isPaid: true, category: 'その他', type: 'その他の醸造酒', name: 'Snow Satoyama Sake - 里山マリアージュ The Heritage(木桶Sparkling)' },
  { booth_number: '31', company_name: '(株)武蔵野酒造', isLimited: true, isPaid: false, category: '清酒', type: '生酒', name: 'スキー正宗 朝一搾り' },
  { booth_number: '31', company_name: '(株)武蔵野酒造', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: 'NOROSHI狼煙' },
  { booth_number: '31', company_name: '(株)武蔵野酒造', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'スキー正宗 プレミアムレギュラー' },
  { booth_number: '31', company_name: '(株)武蔵野酒造', isLimited: true, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'スキー正宗 SAKE※COFFEE (仮)' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越後美人 純米酒' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越後美人 純米大吟醸酒 甘雫' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '吟醸', name: '越後美人 吟醸酒(五百万石100%)' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: '越後美人 純米吟醸酒' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: '越の若竹 純米吟醸酒 Prova' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越の若竹 純米大吟醸酒 SANDO' },
  { booth_number: '32', company_name: '上越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: '越後美人 古酒(H16)' },
  { booth_number: '33', company_name: '(資)竹田酒造店', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: 'かたふね 純米吟醸生原酒' },
  { booth_number: '33', company_name: '(資)竹田酒造店', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'はなじかん' },
  { booth_number: '33', company_name: '(資)竹田酒造店', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'かたふね 純米' },
  { booth_number: '33', company_name: '(資)竹田酒造店', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '大吟醸 20年古酒' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 越の白鳥Gold ND 山田錦' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸 越の白鳥 越淡麗 生原酒' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米酒 越の白鳥 なごり雪 生原酒' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '男帝 暁(あかつき)' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'ONI YAMMACHO RED' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: 'KEG山間 雄町' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: 'KEG山間 五百万石' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越の白鳥ND 一合缶' },
  { booth_number: '34', company_name: '新潟第一酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '越の白鳥ND 一合缶' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '大吟醸' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸KENICHIRO 雄町' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '特別本醸造 真' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米 五百万石' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '柱焼酎仕込み' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: '特別本醸造 真・純米大吟醸300mlセット' },
  { booth_number: '35', company_name: '千代の光酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: 'カップ酒' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '無濾過生原酒 AYUMASAMUNE' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸生酒 初鮎 HATSUAYU' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸 150周年記念酒' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'おりがらみ' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '発泡性清酒 Sweetfish ブルーラベル' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'にごり酒 さるはし~チルチル~' },
  { booth_number: '36', company_name: '鮎正宗酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米にごり酒 さくらいろ ~SAKURAIRO~' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: 'よしかわ杜氏 大辛口 たる酒原酒' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '有りがたし 純米酒' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: 'よしかわ杜氏 大辛口 冴' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '純米かんきつ酒' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '純米梅酒' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '純米梅酒' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: 'よしかわ杜氏 大吟醸' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: 'よしかわ杜氏 大吟醸' },
  { booth_number: '37', company_name: '(株)よしかわ杜氏の郷', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '天恵楽 純米大吟醸Classic' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '佐渡金山秘蔵古酒 大吟醸BY2019' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '真野鶴「万穂」酒の陣限定生酒' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: '真野鶴「実来」酒の陣限定生酒' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '真野鶴 大吟醸無濾過生原酒' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: 'シークレット酒' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'かなでる純米大吟醸Pizzicato' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '超ブラック真野鶴 純米大吟醸' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '真野鶴「万穂」' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '真野鶴「実来」' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '真野鶴「万穂」' },
  { booth_number: '38', company_name: '尾畑酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '真野鶴「実来」' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '鑑評会用貯蔵大吟醸限定版' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '鑑評会用貯蔵大吟醸限定版12.年古酒' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '氷の雫 大吟醸無濾過生原酒' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '吟田川純米吟醸無濾過生' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: 'レッツゴー吟田川無濾過生原酒' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '吟田川特別純米' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '吟田川特別本醸造' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '吟田川特別純米' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '吟田川特別本醸造' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '吟田川特別本醸造カップ' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '雪洞' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '雪洞' },
  { booth_number: '39', company_name: '代々菊醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '吟田川純米吟醸' },
  { booth_number: '40', company_name: '加賀の井酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'KAGANOI たかね錦 生原酒' },
  { booth_number: '40', company_name: '加賀の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '加賀の井 純米大吟醸 雄町 生原酒' },
  { booth_number: '40', company_name: '加賀の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '加賀の井 純米酒「超辛口」' },
  { booth_number: '40', company_name: '加賀の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '加賀の井 純米吟醸' },
  { booth_number: '40', company_name: '加賀の井酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 白藤郷' },
  { booth_number: '41', company_name: '加茂錦酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'SAKE NO JIN EDITION' },
  { booth_number: '41', company_name: '加茂錦酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '梅酒' },
  { booth_number: '42', company_name: '葵酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: 'セット売り', name: 'にいがた酒の陣2026限定 葵とあべ コラボ2本セット' },
  { booth_number: '42', company_name: '葵酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: 'Maison Aoi 水縹 Unfiltered' },
  { booth_number: '42', company_name: '葵酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: 'Maison Aoi 白菫' },
  { booth_number: '42', company_name: '葵酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: '新潟県内限定 新・長陵' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '六郎次 赤 かすみ酒 生' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '米百俵 大吟醸' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '米百俵 純米酒' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '米百俵 伝統の酒 普通酒' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '米百俵 しぼりたて原酒' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '米百俵 純米酒 白麹仕込み' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '六郎次 黒 純米吟醸 越淡麗' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '常在戦場 純米吟醸' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '常在戦場 純米酒' },
  { booth_number: '43', company_name: '栃倉酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '米百俵 梅酒 酒蔵仕込み' },
  { booth_number: '44', company_name: '(有)加藤酒造店', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '普通酒 金鶴' },
  { booth_number: '44', company_name: '(有)加藤酒造店', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '本醸造 金鶴' },
  { booth_number: '44', company_name: '(有)加藤酒造店', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '大吟醸 金鶴' },
  { booth_number: '44', company_name: '(有)加藤酒造店', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米 風和 しぼりたて生' },
  { booth_number: '44', company_name: '(有)加藤酒造店', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米 拓' },
  { booth_number: '44', company_name: '(有)加藤酒造店', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: '金鶴 生酒' },
  { booth_number: '45', company_name: '頚城酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越路乃紅梅 花と雪 HANA' },
  { booth_number: '45', company_name: '頚城酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越路乃紅梅 花と雪 YUKI' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '至 大吟醸 50% 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '真稜 純米大吟醸 50% 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '真稜 純米大吟醸 50% 生にごり' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '真稜 山廃純米大吟醸 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '至 純米吟醸 生原酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '至 純米吟醸 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '至 純米 生原酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '至 純米 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '至 純米酒 生にごり' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '一味真 特別本醸造 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '普通酒', name: '真稜 普通酒 生酒' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '真稜 ワンカップ' },
  { booth_number: '46', company_name: '逸見酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: 'SECRET' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'サビ猫ロック 猫の陣2026' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'サビ猫ロック rust note 赤' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'サビ猫ロック rust note 黒' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'サビ猫ロック premium 銀' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'shubonne にごり なま' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '月不見の池 清酒' },
  { booth_number: '47', company_name: '猪又酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: 'サビ猫ロック DRY!DRY!!DRY!!!なま (試飲のみ 1杯)' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 妙髙山 糸 雄町磨き三割' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 妙髙山 HANEUMA' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '妙髙山 UCHOTEN 純米大吟醸 越淡麗 生原酒' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 妙髙山' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '吟醸 越乃雪月花 しぼりたて生' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '辛口原酒 妙髙山' },
  { booth_number: '48', company_name: '妙高酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'セット売り', name: '妙高リキュール3本セット' },
  { booth_number: '49', company_name: '田中酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '普通酒', name: '酒の陣限定酒 本辛口' },
  { booth_number: '49', company_name: '田中酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米大吟醸~ファーストアタック~' },
  { booth_number: '49', company_name: '田中酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '吟醸生貯蔵(ぎんなま)' },
  { booth_number: '49', company_name: '田中酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: '太刀無名一文字 山鳥毛' },
  { booth_number: '49', company_name: '田中酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'QRコード酒「N」' },
  { booth_number: '49', company_name: '田中酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '黒松' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '美守' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '雪中梅 特別本醸造' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '雪中梅 雪中貯蔵純米原酒' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '雪中梅 特別本醸造' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '雪中梅' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '雪中梅' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '雪中梅' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '雪中梅' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: true, category: '清酒', type: '原酒', name: '雪中梅 にごり酒 シズリユキ 純米吟醸' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '雪中梅 梅酒' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '雪中梅純米生原酒別誂' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: true, category: '清酒', type: '原酒', name: '雪中梅 にごり酒 シズリユキ 純米' },
  { booth_number: '50', company_name: '(株)丸山酒造場', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: 'エセイエ' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '雪鶴 純米大吟醸 生原酒' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '雪鶴 純米吟醸 無濾過生原酒' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '雪鶴 純米吟醸' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '雪鶴 純米吟醸' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '雪鶴 本醸造' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '雪鶴 大辛口ブラック' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: 'ゆきつるスパークリング霞' },
  { booth_number: '51', company_name: '田原酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '雪鶴 大吟醸 秘蔵古酒' },
  { booth_number: '52', company_name: '加藤酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越後屋 米ラベル 純米大吟醸' },
  { booth_number: '52', company_name: '加藤酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後屋 米ラベル にごり' },
  { booth_number: '53', company_name: '(株)小山酒造店', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 醸し香 金' },
  { booth_number: '53', company_name: '(株)小山酒造店', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '吟醸 醸し香 藍' },
  { booth_number: '53', company_name: '(株)小山酒造店', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米 醸し香 翠' },
  { booth_number: '53', company_name: '(株)小山酒造店', isLimited: true, isPaid: false, category: '清酒', type: 'その他の醸造酒', name: '醸し香 にごり' },
  { booth_number: '53', company_name: '(株)小山酒造店', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '大吟醸原酒 越後自慢' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: '雅楽代〜佐州〜 酒の陣別誂' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: '雅楽代〜鴇羽〜 酒の陣別誂生酒' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: '雅楽代〜瑞華〜 酒の陣別誂' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: '雅楽代〜竜王〜 酒の陣別誂' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: '雅楽代〜六華〜 酒の陣別誂' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: 'リキュール', type: 'リキュール', name: '秘密のリキュール ライチ' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: 'リキュール', type: 'リキュール', name: '秘密のリキュール レモン' },
  { booth_number: '54', company_name: '天領盃酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '原酒', name: 'ナイショ☆' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '麒麟山 伝統辛口' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '麒麟山 超辛口' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '麒麟山 やわらか' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: 'セット売り', name: '麒麟山 3本セットB' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '麒麟山 レモネード' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '麒麟山 酒の陣2026限定' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '麒麟山 FUMOTO' },
  { booth_number: '55', company_name: '麒麟山酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '麒麟山 月のしずり' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'TAKARAYAMAコシヒカリ' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: 'TAKARAYAMA新之助' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'たからやま 純米生貯蔵酒 春の陽に' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'たからやま いちご' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'たからやま お茶' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '金の実を見つけた猫 ワイン樽熟成' },
  { booth_number: '56', company_name: 'たからやま醸造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '金の実を見つけた猫 ワイン樽熟成' },
  { booth_number: '57', company_name: 'LAGOON', isLimited: true, isPaid: true, category: 'BREWERY(同)', type: 'その他', name: 'その他の醸造酒 【酒の陣限定】令和7年度の挑戦 越淡麗 純米大吟醸メソッド' },
  { booth_number: '57', company_name: 'LAGOON', isLimited: false, isPaid: true, category: 'その他', type: 'その他の醸造酒', name: '【麒麟山&冨士美園コラボ・酒の陣先行】レゾネコ 梅と茶' },
  { booth_number: '57', company_name: 'LAGOON', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: '【金賞受賞】HOP SAKE ほっぺ' },
  { booth_number: '57', company_name: 'LAGOON', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: '【季節限定】酔いどれ洋梨 槽搾り生' },
  { booth_number: '57', company_name: 'LAGOON', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: '【飲むピザ】SAKEマルゲリータ' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越弌 純米吟醸' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '越弌 オルデラン' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '越弌 スパークリング スピーダー' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越後鶴亀 純米' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越後鶴亀 ワイン酵母仕込み 純米吟醸' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越王 純米大吟醸 鼉竜鏡' },
  { booth_number: '58', company_name: '(株)越後鶴亀', isLimited: false, isPaid: true, category: '清酒', type: '非公開', name: '越後鶴亀 12stamps' },
  { booth_number: '59', company_name: 'ふじの井酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '無濾過生原酒 搾酒' },
  { booth_number: '59', company_name: 'ふじの井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'うずまき <黒>' },
  { booth_number: '59', company_name: 'ふじの井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: 'うずまき <白>' },
  { booth_number: '59', company_name: 'ふじの井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: 'さえずりの里' },
  { booth_number: '59', company_name: 'ふじの井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: 'レトロ' },
  { booth_number: '60', company_name: '(株)DHC酒造', isLimited: true, isPaid: false, category: '清酒', type: '非公開', name: '【酒の陣限定】カヤマライト先行試作型' },
  { booth_number: '60', company_name: '(株)DHC酒造', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '【酒の陣限定】越乃梅里 大吟醸無濾過生原酒 越淡麗磨き35%' },
  { booth_number: '60', company_name: '(株)DHC酒造', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '【酒の陣限定】越乃梅里 純米大吟醸原酒' },
  { booth_number: '60', company_name: '(株)DHC酒造', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: '嘉山 純米吟醸 亀口直採り 無濾過生原酒' },
  { booth_number: '60', company_name: '(株)DHC酒造', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '越乃梅里 大吟醸 越淡麗磨き35% 180mlボトル缶' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '普通酒', name: '【酒の陣限定】極超 亀口 直詰め' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: 'READY!LADY!READY! そらとなでしこ 純米大吟醸' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '彌彦 極' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '彌彦 極 純米' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: true, category: 'リキュール', type: 'リキュール', name: '弥彦浪漫 苺酒' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: true, category: 'リキュール', type: 'リキュール', name: '弥彦浪漫 苺酒' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '弥彦浪漫 梅酒' },
  { booth_number: '61', company_name: '弥彦酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '弥彦浪漫 梅酒' },
  { booth_number: '62', company_name: '今代司酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 今代司 酒の陣' },
  { booth_number: '62', company_name: '今代司酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '錦鯉 黄金' },
  { booth_number: '62', company_name: '今代司酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: '錦鯉' },
  { booth_number: '62', company_name: '今代司酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'ブラック今代司 極辛口 純米酒' },
  { booth_number: '62', company_name: '今代司酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'IMA 牡蠣のための日本酒' },
  { booth_number: '62', company_name: '今代司酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '人と 木と ひととき 純米酒 木桶仕込み' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: '越乃鹿六 プレミアム 無濾過生原酒' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: '越乃鹿六 プレミアム' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越乃鹿六' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米吟醸', name: 'ガンガラシバナ 無濾過生原酒' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'ガンガラシバナ' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米吟醸', name: '試験醸造第2弾' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '菅名岳 特別純米 九' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'KAROKU LIGHT' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '酔星' },
  { booth_number: '63', company_name: '近藤酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '酔星フラワーカップ' },
  { booth_number: '64', company_name: '高野酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越路吹雪 蔵なま酒 純米大吟醸 無濾過生原酒' },
  { booth_number: '64', company_name: '高野酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越路吹雪 梅酒 Premium' },
  { booth_number: '64', company_name: '高野酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越路吹雪 柚子酒 Premium' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '峰乃白梅 本生酒 純米 うすにごり' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '発泡', name: '峰乃白梅 泡恋スパークリング' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: '菱湖 純米大吟醸 愛山 磨き35 五年氷温熟成' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '菱湖 大吟醸 山田錦 磨き35 五年氷温熟成' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '菱湖 純米大吟醸 おりがらみ生' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '菱湖 純米吟醸' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '菱湖 純米吟醸 出羽燦々 無濾過生' },
  { booth_number: '65', company_name: '峰乃白梅酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '菱湖 純米ドライ' },
  { booth_number: '66', company_name: '(株)サケアイ', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: 'SAKENOVA Crafted Series Brew Note 002' },
  { booth_number: '66', company_name: '(株)サケアイ', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: 'SAKENOVA Crafted Series Brew Note 003' },
  { booth_number: '66', company_name: '(株)サケアイ', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: 'SAKENOVA Crafted Series Brew Note 004' },
  { booth_number: '66', company_name: '(株)サケアイ', isLimited: false, isPaid: false, category: 'その他', type: 'その他の醸造酒', name: 'SAKENOVA Crafted Series Brew Note 005' },
  { booth_number: '67', company_name: '君の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '君の井 雪解雫' },
  { booth_number: '67', company_name: '君の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 恵信 越淡麗 無濾過原酒壱度火入れ' },
  { booth_number: '67', company_name: '君の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '君の井 普通酒' },
  { booth_number: '67', company_name: '君の井酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '君の井 山廃純米' },
  { booth_number: '67', company_name: '君の井酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '君の井 山廃純米大吟醸 無濾過雪中貯蔵' },
  { booth_number: '68', company_name: '宮尾酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '〆張鶴 純' },
  { booth_number: '68', company_name: '宮尾酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '〆張鶴 大吟醸 盞' },
  { booth_number: '68', company_name: '宮尾酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '〆張鶴 純米吟醸生原酒 春しぼり' },
  { booth_number: '68', company_name: '宮尾酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '〆張鶴 梅酒' },
  { booth_number: '68', company_name: '宮尾酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '〆張鶴 ツルカップ' },
  { booth_number: '68', company_name: '宮尾酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '〆張鶴 純米大吟醸 GREEN LABEL' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越乃寒梅 灑 純米吟醸' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越乃寒梅 灑 純米吟醸' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越乃寒梅 浹 純米吟醸' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越乃寒梅 浹 純米吟醸' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃寒梅 Lagoon' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越乃寒梅 大江山産' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越乃寒梅 梅酒' },
  { booth_number: '69', company_name: '石本酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米酒', name: '潟ボール' },
  { booth_number: '70', company_name: '王紋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '王紋 純米大吟醸 無濾過生原酒' },
  { booth_number: '70', company_name: '王紋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '王紋 大吟醸 極辛19' },
  { booth_number: '70', company_name: '王紋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '王紋 純米吟醸 にごり' },
  { booth_number: '70', company_name: '王紋酒造(株)', isLimited: false, isPaid: false, category: 'その他', type: 'セット売り', name: '王紋 ミニチュア3本セット' },
  { booth_number: '70', company_name: '王紋酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '王紋 大吟醸 極辛19 ハイボール' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '菊水 樽酒 純米生原酒' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '菊水 純米大吟醸原酒 2024BY' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '菊水ふなぐち 氷川きよし『ほど酔い酒』ver. 200ml×2本詰' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '菊水大吟醸ふなぐち' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '菊水ふなぐち' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '菊水熟成ふなぐち' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '菊水薫香ふなぐち' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '原酒', name: '菊水ふなぐちスパークリング' },
  { booth_number: '71', company_name: '菊水酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '菊水しぼりたて純米生原酒' },
  { booth_number: '72', company_name: '金升酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: 'ドメーヌ髙橋' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '越後杜氏 純米大吟醸 越淡麗' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'じゅんぎん' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '吟醸', name: '村松' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '雪影' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'MURAMATSU-SAKURA' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'MURAMATSU-SAKURA' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '淼' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '越後杜氏 本醸造辛口' },
  { booth_number: '73', company_name: '金鵄盃酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'アロニアのお酒' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '越後桜38大吟醸' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '越後桜白鳥蔵大吟醸無濾過生原酒' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '越後桜白鳥蔵蔵出し生しぼり' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '越後桜白鳥蔵大吟醸原酒' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '越後桜白鳥純米大吟醸' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '越後桜白鳥蔵大吟醸生しぼり' },
  { booth_number: '74', company_name: '越後桜酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '越後桜白鳥蔵ゆずレモンリキュール' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '紫雲 大洋盛' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別本醸造', name: '辛口特別本醸造 越乃松露' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '特別純米 大洋盛 ボトル缶' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '純米無濾過生原酒 大洋盛' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸 SweetPinkラベル' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '純米吟醸 北翔' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米吟醸', name: '(仮)純米吟醸 酒の陣専売酒' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '大吟醸 大洋盛' },
  { booth_number: '75', company_name: '大洋酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 大洋盛' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越乃八豊 純米吟醸' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越乃八豊 春しぼり純米酒720ml' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '越後の辛口純米生原酒' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '越後の甘口純米生原酒' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'KOSHINO RIKKA 純米一火Limited Edition' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '試験醸造 純米吟醸 山田錦 豊' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: true, isPaid: false, category: '清酒', type: '純米酒', name: '越後酒造場 生貯蔵酒' },
  { booth_number: '76', company_name: '(株)越後酒造場', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '越後純米酒300ml三種飲み比べ' },
  { booth_number: '77', company_name: '塩川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '願人 山廃純米酒' },
  { booth_number: '77', company_name: '塩川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '新雪物語 純米吟醸' },
  { booth_number: '77', company_name: '塩川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'FISHERMAN SOKUJO' },
  { booth_number: '77', company_name: '塩川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: 'COWBOY YAMAHAI' },
  { booth_number: '77', company_name: '塩川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: 'のぱ 秋' },
  { booth_number: '77', company_name: '塩川酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '越 純米吟醸' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米大吟醸', name: '愛山 愛冴夢 SUPERB' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '愛冴夢 統 (愛山&山田錦)Assemblage' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米酒', name: '愛山 愛冴夢 崇泉' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '代々寶 山田錦 三年古酒' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '山田錦 越乃あじわい' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '低温生貯蔵 大吟醸 代々泉35' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '五頭の酔泉' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '本醸造', name: '飲みくらべ300' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '南高梅 梅酒 梅乃泉' },
  { booth_number: '78', company_name: '越つかの酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '発泡', name: '雪乃雹' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '麒麟 純米大吟醸 プレミアム' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '麒麟 秘蔵酒' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '大吟醸', name: '麒麟 大吟醸袋取り雫酒' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '純米大吟醸', name: '蒲原 純米大吟醸袋取り原酒 越淡麗' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: true, category: '清酒', type: '本醸造', name: '麒麟本醸造濃熟オールド' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '蒲原 無濾過袋取り生貯蔵酒 純米吟醸山田錦' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '蒲原 無濾過袋取り生貯蔵酒 純米吟醸たかね錦' },
  { booth_number: '79', company_name: '下越酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米吟醸', name: '蒲原 純米吟醸 緑' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '白龍 純米大吟醸生原酒' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '白龍 純米吟醸生原酒無濾過' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '大吟醸', name: '白龍 大吟醸生原酒' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: true, isPaid: false, category: '清酒', type: '吟醸', name: '白龍 吟醸にごり酒生' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: 'ワイン酵母仕込み 純米大吟醸' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米大吟醸', name: '純米大吟醸 ワイン酵母仕込み生' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'ヨーグルトリキュールモウモウプレーン' },
  { booth_number: '80', company_name: '白龍酒造(株)', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: 'ふぐひれ酒' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '純米酒', name: '【限定酒】アーティストラベル 笹祝 亀の尾純米無濾過生原酒' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '【限定酒】出品酒 大吟醸 無濾過生原酒' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '発泡', name: '笹祝challenge brew 捌の巻 CLAP! CLAP! SPARKLING' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '特別純米', name: '笹祝 特別純米酒しぼりたて生原酒' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '純米酒', name: '笹印 純米無濾過酒' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '普通酒', name: '笹祝 新潟印' },
  { booth_number: '81', company_name: '笹祝酒造(株)', isLimited: false, isPaid: false, category: '清酒', type: '非公開', name: '笹祝 バンブーシュート-酸貴白低' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: true, isPaid: true, category: '清酒', type: '大吟醸', name: '北雪 大吟醸YK35 中取り生原酒 (720ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '北雪 生酒 酒の陣 限定酒 (720ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: true, isPaid: false, category: '清酒', type: '純米吟醸', name: '北雪 佐渡金山坑道貯蔵酒 酒の陣 限定酒(720ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '北雪 純米大吟醸 遠心分離 鬼夜叉 (720ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: true, isPaid: false, category: '清酒', type: '純米大吟醸', name: '北雪 純米大吟醸 酒の陣限定酒(720ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '北雪 大吟醸YK35 (720ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: false, isPaid: false, category: '清酒', type: '大吟醸', name: '北雪 大吟醸YK35 (300ml)' },
  { booth_number: '82', company_name: '(株)北雪酒造', isLimited: false, isPaid: false, category: 'リキュール', type: 'リキュール', name: '北雪 梅酒 (500ml)' },
];

export interface AppBrewery {
  id: string;
  boothNumber: string;
  name: string;
  region: string;
  sakes: AppSake[];
  color: string;
}

export interface AppSake {
  id: string;
  name: string;
  shortType: string;
  typeColor: string;
  tags: ('限定' | '有料')[];
  rawType: string;
  rawIsLimited: boolean;
  rawIsPaid: boolean;
  rawCompany: string;
  rawCategory: string;
}
